version: '3'
services:
  gateway:
    image: openjdk:11
    ports:
      - 80:80
    environment:
      - nacos_host=http://nacos:8848
      - nacos_password=Xiangxuan123!
    volumes:
      - ./:/home/design
    command: java -jar /home/design/design-gateway-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod

networks:
  default:
    external:
      name: design_default