spring:
  application:
    name: design
  profiles:
    active: win
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
        cache-null-values: true
        time-to-live: 50000
  datasource:
    url: 'jdbc:mysql://114.116.213.241:3306/2018214220?
            createDatabaseIfNotExist=true
            &serverTimezone=Asia/Shanghai'
    username: 2018214220
    password: 2018214220
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jackson:
    default-property-inclusion: non_null # 序列化时忽略空值属性
server:
  port: 8080
my:
  secretkey: R28K42ZEJ8LWRHU5
  salt: 636eac2534bcfcb0

logging:
  level:
    root: warn
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'