spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: http://localhost:8848
        username: nacos
        password: nacos
        namespace: public
    gateway:
      routes:
        - id: design
          predicates:
            - Path=/order-api/**
          uri: lb://design
          filters:
            - StripPrefix=1
            - PrefixPath=/api/